// Development Canvas/Workshop authority fixtures; actual Adapter selection consumer, no real Core.
import test from 'node:test';import assert from 'node:assert/strict';import * as C from '#contracts';
import {createSessionSelectionConsumer} from '../dev/world-manage/session-selection.mjs';
const module=await import('../dev/world-manage/session-fixture.mjs').catch(e=>{if(e.code==='ERR_MODULE_NOT_FOUND')return null;throw e;});
function setup(){assert.ok(module,'published-contract Session/Canvas fixture is missing');
 const profile={profileVersion:'state-profile/v2',nodeFields:['nodeName','param1','param2'],metadataMode:'exact',inventoryMode:'exact',timerMode:'exact',derivedLightMode:'recompute-with-readback'};
 const connections=['A','B'].map(w=>({adapterId:'hanaworlds-adapter-luanti',connectionRef:'c:'+w,worldRef:w,displayName:w,capabilityRevision:'cap',payloadVersion:'0.6.0',readiness:'READY',connectionIncarnationRef:'inc:'+w}));
 const adapter={async call(name,q){const c=connections.find(c=>c.connectionRef===q.connectionRef);const result=name==='DiscoverConnections'?{capabilityRevision:'cap',connections}: {connectionRef:c.connectionRef,worldRef:c.worldRef,connectionIncarnationRef:c.connectionIncarnationRef,payloadVersion:'0.6.0',payloadDigest:'0'.repeat(64),capabilities:{providerRef:'adapter',capabilityRevision:'cap',worldRef:c.worldRef,engineBounds:null,limits:[],recoveryGuarantee:'RECOVERABLE_VERIFIED',stateProfile:profile,sessionDeleteSupported:false,imageMediaTypes:[],model:null,engineGuards:null}};return C.validateBoundResponse('world-adapter/v7',name,q,{contractVersion:'world-adapter/v7',requestId:q.requestId,result,error:null});}};
 const f=module.createSessionWorldFixture({resolveAdapter:()=>adapter});f.registerWorld({worldRef:'A',connectionRef:'c:A'});f.registerWorld({worldRef:'B',connectionRef:'c:B'});
 const consumer=createSessionSelectionConsumer({resolveCanvas:()=>f.canvas,ensureConnection:async(s,ref)=>{await f.readIdentity(s);return (await adapter.call('ReadLocalConnection',{contractVersion:'world-adapter/v7',requestId:'read:'+ref,sessionRef:s,connectionRef:ref})).result;}});
 const sessions=f.directory.sessions;const select=(s,w)=>consumer.select({sessionRef:s,worldRef:w,connectionRef:'c:'+w,expectedRevision:f.precondition(s)});
 return {f,consumer,select,s1:sessions[0].sessionRef,s2:sessions[1].sessionRef};
}
test('trusted G-S directory is sorted; choosing known unbound Session is independent of native connection',async()=>{const {f,consumer,s1}=setup();assert.deepEqual((await f.listSessions()).sessions,f.directory.sessions);const r=await consumer.read({sessionRef:s1,worldRef:'fixture-world-A'});assert.equal(r.selection.status,'UNBOUND');assert.deepEqual(r.inventory.connections,[]);await assert.rejects(f.readIdentity('unknown'),/SESSION_NOT_FOUND/);});
test('G-U consumer unbinds only S1, retaining S2 A and real last context until explicit unbind',async()=>{const {f,consumer,select,s1,s2}=setup();await select(s1,'A');await select(s2,'A');await consumer.unselect({sessionRef:s1,worldRef:'A',expectedRevision:f.precondition(s1)});assert.equal((await consumer.read({sessionRef:s1,worldRef:'A'})).selection.status,'UNBOUND');assert.equal((await consumer.read({sessionRef:s2,worldRef:'A'})).selection.context.activeWorldRef,'A');});
test('retirement reservation blocks new selection and release RETIRED rejects retired world',async()=>{const {f,select,s1}=setup();const call=(n,v)=>f.canvas.call(n,{contractVersion:'canvas/v6',requestId:n,...v});const i=(await call('ListWorldSelections',{worldRef:'B'})).result;const r=(await call('ReserveWorldRetirement',{worldRef:'B',expectedInventoryRevision:i.inventoryRevision})).result;await assert.rejects(select(s1,'B'),/TRANSACTION_CONFLICT/);await call('ReleaseWorldRetirement',{worldRef:'B',reservationRef:r.reservationRef,outcome:'RETIRED'});await assert.rejects(select(s1,'B'),/WORLD_NOT_FOUND/);});
test('unsupported Session delete returns no success and preserves Canvas selection',async()=>{const {f,consumer,select,s1}=setup();await select(s1,'A');const before=await consumer.read({sessionRef:s1,worldRef:'A'});const q={contractVersion:'session/v4',requestId:'delete',sessionRef:s1,expectedRevision:(await f.readIdentity(s1)).sessionRevision};const r=await f.workshop.call('DeleteSession',q);assert.equal(r.error.code,'SESSION_DELETE_UNSUPPORTED');assert.deepEqual((await consumer.read({sessionRef:s1,worldRef:'A'})).selection,before.selection);});
