import test from 'node:test';import assert from 'node:assert/strict';import * as C from '#contracts';
import {createSessionWorldFixture} from '../dev/world-manage/session-fixture.mjs';import {withWorldRetirement} from '../src/world-retirement.mjs';
const module=await import('../dev/world-manage/session-manager.mjs').catch(e=>{if(e.code==='ERR_MODULE_NOT_FOUND')return null;throw e;});
function setup(){assert.ok(module,'independent Session/World manager missing');const worlds=[],active=new Map(),starts=[],deletes=[],errors=new Map(),stops=[];let fixture;
 const profile={profileVersion:'state-profile/v2',nodeFields:['nodeName','param1','param2'],metadataMode:'exact',inventoryMode:'exact',timerMode:'exact',derivedLightMode:'recompute-with-readback'};
 const adapter={async call(name,q){let result,error=null;if(name==='DiscoverConnections')result={capabilityRevision:'cap',connections:[...active.values()].map(x=>({adapterId:'hanaworlds-adapter-luanti',connectionRef:x.connectionRef,worldRef:x.worldRef,displayName:x.worldRef,capabilityRevision:'cap',payloadVersion:'0.6.0',readiness:'READY',connectionIncarnationRef:x.connectionIncarnationRef}))};else if(errors.has(q.connectionRef)){result=null;error={code:errors.get(q.connectionRef),phase:'validate',retryability:'AFTER_NEW_FACTS',mutationState:'NONE',transactionRef:null,causeCode:null,reason:'REQUIRED_FACT_UNKNOWN'};}else if(active.has(q.connectionRef))result=active.get(q.connectionRef);else{result=null;error={code:'CONNECTION_NOT_FOUND',phase:'validate',retryability:'AFTER_NEW_FACTS',mutationState:'NONE',transactionRef:null,causeCode:null,reason:'REQUIRED_FACT_UNKNOWN'};}return C.validateBoundResponse('world-adapter/v7',name,q,{contractVersion:'world-adapter/v7',requestId:q.requestId,result,error});}};
 const local={discover:async()=>worlds,describeFlatWorldCreation:async()=>({ready:true}),createFlatWorld:async({worldName})=>{const row={connectionRef:'c:'+worldName,worldRef:worldName,worldPath:'/own/'+worldName,worldName};worlds.push(row);return row;},acquire:async q=>{starts.push(q.connectionRef);return {...q,leaseRef:'lease:'+q.connectionRef,nativeProcessId:100+starts.length};},pair:async q=>{const row=worlds.find(w=>w.connectionRef===q.connectionRef);const r={connectionRef:row.connectionRef,worldRef:row.worldRef,connectionIncarnationRef:'inc:'+row.worldRef,payloadVersion:'0.6.0',payloadDigest:'0'.repeat(64),capabilities:{providerRef:'adapter',capabilityRevision:'cap',worldRef:row.worldRef,engineBounds:null,limits:[],recoveryGuarantee:'RECOVERABLE_VERIFIED',stateProfile:profile,sessionDeleteSupported:false,imageMediaTypes:[],model:null,engineGuards:null}};active.set(row.connectionRef,r);return r;},stopWorld:async q=>{stops.push(q.connectionRef);errors.delete(q.connectionRef);active.delete(q.connectionRef);return {stopped:true};},describeWorldDeletion:async q=>({connectionRef:q.connectionRef,worldRef:q.worldRef,productCreated:true,dataLoss:{files:1,bytes:10},blockers:active.has(q.connectionRef)?[{code:'WORLD_IN_USE',reason:'RUNNING'}]:[],deletable:!active.has(q.connectionRef)}),deleteWorld:q=>withWorldRetirement(()=>fixture.canvas,q.worldRef,async()=>{deletes.push(q.worldRef);worlds.splice(worlds.findIndex(w=>w.worldRef===q.worldRef),1);return {deleted:true,readback:{listed:false,pathExists:false}};})};
 fixture=createSessionWorldFixture({resolveAdapter:()=>adapter});const manager=module.createSessionManager({local,adapter,fixture,requesterRef:'own',userPath:'/own',foreignActivity:async()=>[],game:{running:()=>false}});return {manager,fixture,starts,deletes,errors,stops};}
test('choosing a trusted fixture Session with zero worlds shows unbound and starts no native engine',async()=>{const f=setup(),s=f.fixture.directory.sessions[0].sessionRef;await f.manager.choose(s);const state=await f.manager.state();assert.equal(state.chosenSession,s);assert.equal(state.sessions[0].connectionState.status,'UNBOUND');assert.deepEqual(f.starts,[]);await assert.rejects(f.manager.choose('unknown'),/SESSION_NOT_FOUND/);});
test('manager two Sessions share A, S1 switches B and back without restarting A or changing S2',async()=>{const f=setup(),[s1,s2]=f.fixture.directory.sessions.map(s=>s.sessionRef);const a=await f.manager.create('A'),b=await f.manager.create('B');await f.manager.select(s1,a.connectionRef);await f.manager.select(s2,a.connectionRef);await f.manager.select(s1,b.connectionRef);const mid=await f.manager.state();assert.equal(mid.sessions[1].selection.context.activeWorldRef,'A');await f.manager.select(s1,a.connectionRef);assert.deepEqual(f.starts,['c:A','c:B']);const preview=await f.manager.preview(a.connectionRef);assert.equal(preview.deletable,false);assert.ok(preview.blockers.some(b=>b.code==='TRANSACTION_CONFLICT'));await assert.rejects(f.manager.confirm(preview.confirmationRef));assert.deepEqual(f.deletes,[]);});
test('unselect preserves the other Session; unused B stops and deletes through Canvas retirement',async()=>{const f=setup(),[s1,s2]=f.fixture.directory.sessions.map(s=>s.sessionRef);const a=await f.manager.create('A'),b=await f.manager.create('B');await f.manager.select(s1,a.connectionRef);await f.manager.select(s2,a.connectionRef);await f.manager.select(s1,b.connectionRef);await f.manager.unselect(s1);await f.manager.stop(b.connectionRef);const p=await f.manager.preview(b.connectionRef);assert.equal(p.deletable,true);await f.manager.confirm(p.confirmationRef);assert.deepEqual(f.deletes,['B']);const s=await f.manager.state();assert.equal(s.sessions[1].connectionState.status,'CONNECTED');assert.equal(s.sessions[0].selection.status,'UNBOUND');});

test('reselecting unavailable native connection first completes original owner retirement then starts one new connection',async()=>{const f=setup(),s1=f.fixture.directory.sessions[0].sessionRef,a=await f.manager.create('A');await f.manager.select(s1,a.connectionRef);f.errors.set(a.connectionRef,'CURRENT_WORLD_MISMATCH');await f.manager.select(s1,a.connectionRef);assert.deepEqual(f.stops,['c:A']);assert.deepEqual(f.starts,['c:A','c:A']);});

test('reconnecting after inventory has revoked an exited native lease retires the original ownership record',async()=>{const f=setup(),s=f.fixture.directory.sessions[0].sessionRef,a=await f.manager.create('A');await f.manager.select(s,a.connectionRef);f.errors.set(a.connectionRef,'WORLD_NOT_BOUND');await f.manager.select(s,a.connectionRef);assert.deepEqual(f.stops,['c:A']);assert.deepEqual(f.starts,['c:A','c:A']);});
