import {spawn,execFileSync} from 'node:child_process';
import {readFileSync,writeFileSync} from 'node:fs';
import {join} from 'node:path';
import {once} from 'node:events';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
const input=JSON.parse(readFileSync(0,'utf8')), root=process.env.HW_COMPONENT_ROOT, run=process.env.HW_LOCAL_RUN;
const evidence=join(run,'_evidence'),runtime=join(root,'hanaworlds-dsh');
const child=spawn(join(root,'runtime/hanaworlds-runtime/node/bin/node'),['--expose-internals',join(runtime,'node_modules/@deepseek-ai/dsh-desktop-host/lib/index.js'),runtime,input.profile],{cwd:input.profile,env:{HOME:input.home,DSH_HOME:input.home,PATH:'/usr/bin:/bin:/usr/sbin:/sbin',HANAWORLDS_HOST_PORT:String(input.hostPort),DSH_TELEMETRY_MODE:'DISABLED',DSH_TELEMETRY_DISABLED:'1'},stdio:['ignore','pipe','pipe','ipc']});
let output='';const capture=b=>{output+=String(b).replace(/([?&]token=)[^\s"<>]+/g,'$1[REDACTED]');};child.stdout.on('data',capture);child.stderr.on('data',capture);
const receipt={level:'REAL_RUNTIME packed Adapter/public DSH registry/native Host/Luanti; account/game/profile/selection/native protocol client FIXTURE',hostPid:child.pid,steps:[]};
try {
 const ready=await new Promise((yes,no)=>{const t=setTimeout(()=>no(Error('HOST_READY_TIMEOUT')),25000);child.on('message',m=>{if(m.type==='ready'){clearTimeout(t);yes(m);}else if(m.type==='fatal'){clearTimeout(t);no(Error('HOST_FATAL'));}});child.once('exit',()=>{clearTimeout(t);no(Error('HOST_EARLY_EXIT'));});});
 const login=await fetch(ready.url,{redirect:'manual'}),cookie=login.headers.get('set-cookie').split(';')[0];
 const call=async(method,input)=>{const response=await fetch(new URL('/component-local-world',ready.url),{method:'POST',headers:{cookie,'content-type':'application/json'},body:JSON.stringify({method,input})});assert.equal(response.status,200);return response.json();};
 const good=async(method,input)=>{const result=await call(method,input);assert.equal(result.ok,true,`${method}: ${result.code}`);return result.result;};
 const denied=async(method,input)=>{const result=await call(method,input);assert.equal(result.ok,false,`${method} must deny`);return result.code;};
 await good('setRoots',{roots:[input.worldsRoot]});
 const [missing]=await good('discover');assert.equal(missing.worldPath,input.worldPath);assert.equal(missing.payloadStatus,'MISSING');assert.equal(missing.worldRef,null);receipt.steps.push({missing});
 const request={connectionRef:missing.connectionRef,requesterRef:'fixture-trusted-host-selection',userPath:input.userPath,username:'NativeAdmin',password:input.passwords.NativeAdmin,action:'PROVISION_PAYLOAD'};
 const leaseQuery=lease=>({leaseRef:lease.leaseRef,requesterRef:request.requesterRef,connectionRef:request.connectionRef});
 receipt.steps.push({unknown:await denied('acquire',{...request,connectionRef:'local:unknown'}),unpaired:await denied('acquire',{...request,action:'BIND_RUNNING_WORLD'}),nonAdmin:await denied('acquire',{...request,username:'NativeUser',password:input.passwords.NativeUser})});
 const provisionLease=await good('acquire',request);assert.equal(provisionLease.action,'PROVISION_PAYLOAD');
 receipt.steps.push({provisionLease,wrongRequester:await denied('provision',{...leaseQuery(provisionLease),requesterRef:'wrong'}),wrongWorld:await denied('provision',{...leaseQuery(provisionLease),connectionRef:'local:wrong'}),forged:await denied('provision',{...leaseQuery(provisionLease),leaseRef:'forged'})});
 const installed=await good('provision',leaseQuery(provisionLease));
 assert.throws(()=>execFileSync('/bin/ps',['-p',String(provisionLease.nativeProcessId),'-o','pid='],{encoding:'utf8'}));
 const expired=await denied('provision',leaseQuery(provisionLease));
 const [world]=await good('discover');assert.ok(world.worldRef);assert.equal(world.payloadVersion,'0.2.5');assert.notEqual(world.payloadStatus,'MISSING');receipt.steps.push({installed,world,installingEngineExited:true,expired});
 const binding=await good('acquire',{...request,action:'BIND_RUNNING_WORLD'}),query=leaseQuery(binding);
 const paired=await good('pair',query);assert.equal(paired.paired,true);assert.equal(paired.worldRef,world.worldRef);
 receipt.steps.push({paired,wrongRead:await denied('readCurrentGrants',{...query,connectionRef:'local:other'})});
 const initial=await good('readCurrentGrants',query);assert.deepEqual(initial.grants,[]);receipt.steps.push({nativeAdminDoesNotGrantBuild:initial});
 const command=execFileSync('/bin/ps',['-p',String(binding.nativeProcessId),'-o','command='],{encoding:'utf8'}).trim();
 const configPath=command.match(/--config (.*?) --logfile/)[1],config=readFileSync(configPath,'utf8');
 assert.match(config,/secure.http_mods = hanaworlds_adapter/);assert.match(config,/secure.enable_security = true/);assert.match(config,/secure.trusted_mods =\s*\n/);assert.match(config,/name =\s*\n/);
 const sockets=execFileSync('/usr/sbin/lsof',['-nP','-a','-p',String(binding.nativeProcessId),'-iUDP','-Fpn'],{encoding:'utf8'}),port=Number(sockets.match(/n127\.0\.0\.1:(\d+)/)[1]);
 writeFileSync(join(evidence,'actual-engine-config.json'),JSON.stringify({engineCommand:command,config,port,world:input.worldPath},null,2));
 const native=(Command,Button='')=>JSON.parse(execFileSync(process.env.HW_NATIVE_CLIENT,[],{input:JSON.stringify({Port:port,Username:'NativeRevoker',Password:input.passwords.NativeRevoker,Command,Button}),encoding:'utf8',timeout:18000}));
 receipt.steps.push({enable:native('/hanaworlds_auto','hw_auto_enable')});
 const automatic=await good('readCurrentGrants',query);assert.ok(automatic.grants.length>0);assert.ok(automatic.grants.every(g=>g.worldRef===world.worldRef&&g.scope==='WORLD_BUILD_WITH_ENGINE_PROTECTION'));
 receipt.steps.push({automatic});
 receipt.steps.push({disable:native('/hanaworlds_auto','hw_auto_disable')});
 const afterDisable=await good('readCurrentGrants',query);assert.deepEqual(afterDisable.grants,[]);receipt.steps.push({afterDisable});
 receipt.steps.push({enableAgain:native('/hanaworlds_auto','hw_auto_enable')});
 const enabledAgain=await good('readCurrentGrants',query);assert.ok(enabledAgain.grants.length>0);
 receipt.steps.push({revokeBuild:native('/revoke NativeAdmin worldedit')});
 const revokedBuild=await good('readCurrentGrants',query);assert.deepEqual(revokedBuild.grants,[]);receipt.steps.push({revokedBuild});
 receipt.steps.push({revokeOperator:native('/revoke NativeAdmin server')});
 receipt.steps.push({operatorRevoked:await denied('inspect',query),currentReadDenied:await denied('readCurrentGrants',query),oldPairDenied:await denied('pair',query)});
 receipt.packageSha256=createHash('sha256').update(readFileSync(join(run,'hanaworlds-adapter-luanti-0.2.5.tgz'))).digest('hex');
 writeFileSync(join(evidence,'public-runtime-observation.json'),JSON.stringify(receipt,null,2)+'\n');console.log(JSON.stringify(receipt,null,2));
} finally {
 writeFileSync(join(evidence,'public-runtime-progress.json'),JSON.stringify(receipt,null,2)+'\n');
 if(child.connected)child.send({type:'shutdown'},()=>{});
 if(child.exitCode===null&&child.signalCode===null){const t=setTimeout(()=>child.kill('SIGTERM'),10000);await once(child,'exit');clearTimeout(t);}
 writeFileSync(join(evidence,'public-host-output.log'),output);
 writeFileSync(join(evidence,'host-shutdown.json'),JSON.stringify({pid:child.pid,exitCode:child.exitCode,signal:child.signalCode},null,2));
 assert.equal(child.signalCode,null);assert.equal(child.exitCode,0);
}
